name = "health-connect-sync-api"
main = "src/index.ts"
compatibility_date = "2026-02-24"
workers_dev = true

[[d1_databases]]
binding = "DB"
database_name = "health_connect_sync"
database_id = "4f34f044-357e-4d00-bca6-85365ae2210b"
remote = false
migrations_dir = "migrations"
